# Generated by Django 4.0.3 on 2022-03-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV_ables_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtype',
            old_name='lable',
            new_name='label',
        ),
    ]
