# Generated by Django 4.0.3 on 2022-03-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV_ables_api', '0002_rename_lable_jobtype_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='framework',
            old_name='lable',
            new_name='label',
        ),
    ]
