# Generated by Django 4.0.3 on 2022-03-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV_ables_api', '0003_rename_lable_framework_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='lable',
            new_name='label',
        ),
    ]
