# Generated by Django 4.0.3 on 2022-03-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_ables_api', '0004_rename_lable_language_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_yr',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
