# Generated by Django 4.0.3 on 2022-03-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV_ables_api', '0005_alter_experience_end_yr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='framework',
        ),
    ]
