# Generated by Django 4.0.3 on 2022-03-14 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CV_ables_api', '0006_remove_experience_framework'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='CV_ables_api.applicant'),
        ),
    ]
