# Generated by Django 4.0.3 on 2022-03-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV_ables_api', '0007_project_applicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='jobtype',
            new_name='job_type',
        ),
    ]
