# Generated by Django 4.0.3 on 2022-03-15 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CV_ables_api', '0008_rename_jobtype_mission_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceVita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_vita', to='CV_ables_api.experience')),
                ('vita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_vita', to='CV_ables_api.vita')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_lang', to='CV_ables_api.applicant')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_lang', to='CV_ables_api.experience')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_lang', to='CV_ables_api.language')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_lang', to='CV_ables_api.project')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_frame', to='CV_ables_api.applicant')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_frame', to='CV_ables_api.experience')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_frame', to='CV_ables_api.framework')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_frame', to='CV_ables_api.project')),
            ],
        ),
        migrations.CreateModel(
            name='EducationVita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_vita', to='CV_ables_api.education')),
                ('vita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_vita', to='CV_ables_api.vita')),
            ],
        ),
    ]
