# Generated by Django 4.0.3 on 2022-03-15 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CV_ables_api', '0009_experiencevita_experiencelang_experienceframe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='CV_ables_api.applicant'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='CV_ables_api.jobtype'),
        ),
    ]
