# Generated by Django 4.0.3 on 2022-03-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_ables_api', '0010_alter_mission_applicant_alter_mission_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='duties',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
