# Generated by Django 4.0.3 on 2022-03-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_ables_api', '0011_experience_duties'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
