# Generated by Django 4.0.3 on 2022-03-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_ables_api', '0012_prospectstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectstatus',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
