# Generated by Django 4.0.3 on 2022-03-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_ables_api', '0013_alter_prospectstatus_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='markedvita',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='notes',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
