# Generated by Django 4.0.3 on 2022-03-20 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CV_ables_api', '0014_prospect_markedvita_prospect_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='prospectstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospect', to='CV_ables_api.prospectstatus'),
        ),
    ]
