# Generated by Django 4.0.3 on 2022-03-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_ables_api', '0016_alter_prospect_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='notes',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
