# Generated by Django 4.0.3 on 2022-03-21 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CV_ables_api', '0017_alter_prospect_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vita',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vita', to='CV_ables_api.prospect'),
        ),
    ]
